drop type if exists grocery;
create type grocery as enum (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

create table if not exists shopping_list (
    id integer  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text not null,
    price decimal(12, 2) not null,
    date_added timestamp not null default now(),
    checked boolean not null default false,
    category grocery not null
)